### ISSUE TITLE
XcodeVersionedName.munki FileMover: [Errno 66] Directory not empty

### ISSUE THREAD

**Issue by macjustice** [facebook/Recipes-for-AutoPkg#31]
After once successful `autopkg run XcodeVersionedName.munki`, subsequent runs produce a `[Errno 66] Directory not empty` error. Maybe the `PathDeleter` process in `Xcode.download.recipe` should have moar paths?

**Comment by nmcspadden** [comment]
Should be fixed in 50c23114fbfdc3ee780ecd25cf3c549d8ac3a210. Please test and let me know.

**Comment by macjustice** [comment]
Not fixed, here's better verbosity:
```
FileMover
{'Input': {'source': u'/Users/macj/Library/AutoPkg/Cache/local.munki.XcodeVersionedName/Xcode_unpack/Xcode.app',
           'target': u'/Users/macj/Library/AutoPkg/Cache/local.munki.XcodeVersionedName/Xcode_11.0.0.app'}}
[Errno 66] Directory not empty
```
I might be misunderstanding how Autopkg does caching, but I think this implies that the PathDeleter processor in [`XcodeVersionedName.munki.recipe`](https://github.com/facebook/Recipes-for-AutoPkg/blob/50c23114fbfdc3ee780ecd25cf3c549d8ac3a210/Xcode/XcodeVersionedName.munki.recipe#L110) and [`Xcode.munki.recipe`](https://github.com/facebook/Recipes-for-AutoPkg/blob/50c23114fbfdc3ee780ecd25cf3c549d8ac3a210/Xcode/Xcode.munki.recipe#L89) should include the path `%RECIPE_CACHE_DIR%/%NAME%_%major_version%.%minor_version%.%patch_version%.app` and `%RECIPE_CACHE_DIR%/%NAME%.app`, respectively.

I can PR if that looks correct to you.

**Comment by nmcspadden** [comment]
Hmm. I was unable to repro this by running it twice. I'll try again.

**Comment by nmcspadden** [comment]
Well, I beg your pardon because I apparently can't read. I found the bug in XcodeVersionedName.munki and testing it now.

**Comment by nmcspadden** [comment]
This should now be actually fixed by https://github.com/facebook/Recipes-for-AutoPkg/commit/b456170dea4ceacd3606c9d69965cc3516bccf25. Please test and let me know.

**Comment by macjustice** [comment]
✅
